### PR TITLE
Date Time Picker Added

### PR DESCRIPTION
**Pull request by Rishi22-Coding**
Signed-off-by: Saptarshi Patra <saptarshi.patra.22@gmail.com>

# Description

#65 Changed date time field from text to date time picker

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Rishi22-Coding** [comment]
Screenshot from 2021-10-03 11-38-21

**Comment by irsayvid** [comment]
hey @Rishi22-Coding can you attach screenshot of how the date time picker looks on clicking it

**Comment by Rishi22-Coding** [comment]
Screenshot from 2021-10-03 12-03-43
@irsayvid have a look.

**Comment by Rishi22-Coding** [comment]
Screenshot from 2021-10-03 12-04-42
@irsayvid

**Comment by irsayvid** [comment]
cool

**Pull request merged**
